//! Maintainer-only curl 8.22 manifest; never invoked by a consumer build.
//! From the repository root: zig run native/generate-curl-sources.zig -- [--check]
//! Accepts only literal filename lists and CSOURCES references, not Make syntax.
const std = @import("std");

fn fail(comptime format: []const u8, args: anytype) noreturn {
    std.debug.print("error: " ++ format ++ "\n", args);
    std.process.exit(1);
}

pub fn main() void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    run(arena.allocator()) catch |err| fail("{s}", .{@errorName(err)});
}

fn run(a: std.mem.Allocator) !void {
    const args = try std.process.argsAlloc(a);
    const check = args.len == 2 and std.mem.eql(u8, args[1], "--check");
    if (args.len != 1 and !check) {
        if (args.len == 2 and std.mem.eql(u8, args[1], "--help")) {
            try std.fs.File.stdout().writeAll("Usage: zig run native/generate-curl-sources.zig -- [--check]\nRun from the repository root. --check reports drift without writing files.\n");
            return;
        }
        fail("expected no arguments or --check; use --help for usage", .{});
    }
    const input = "vendor/curl/lib/Makefile.inc";
    const raw = std.fs.cwd().readFileAlloc(a, input, 1024 * 1024) catch |err|
        fail("read {s}: {s}; run from the repository root", .{ input, @errorName(err) });
    var assignments = std.StringHashMap([]const u8).init(a);
    var logical: std.ArrayList(u8) = .empty;
    var lines = std.mem.splitScalar(u8, raw, '\n');
    while (lines.next()) |line| {
        const uncommented = line[0 .. std.mem.indexOfScalar(u8, line, '#') orelse line.len];
        const continued = std.mem.endsWith(u8, uncommented, "\\");
        try logical.appendSlice(a, if (continued) uncommented[0 .. uncommented.len - 1] else uncommented);
        if (continued) {
            try logical.append(a, ' ');
            continue;
        }
        const entry = std.mem.trim(u8, logical.items, " \t\r");
        if (entry.len != 0) {
            const equal = std.mem.indexOf(u8, entry, " =") orelse
                fail("unexpected Makefile.inc assignment: {s}", .{entry});
            const name = entry[0..equal];
            for (name) |c| {
                if (!std.ascii.isAlphanumeric(c) and c != '_') fail("invalid assignment name: {s}", .{name});
            }
            if (assignments.contains(name)) fail("duplicate Makefile.inc assignment: {s}", .{name});
            try assignments.put(try a.dupe(u8, name), try a.dupe(u8, entry[equal + 2 ..]));
        }
        logical.clearRetainingCapacity();
    }
    if (logical.items.len != 0) fail("unterminated Makefile.inc continuation", .{});
    const sources = assignments.get("CSOURCES") orelse fail("Makefile.inc has no CSOURCES assignment", .{});
    var references = std.mem.tokenizeAny(u8, sources, " \t\r");
    var files: std.ArrayList([]const u8) = .empty;
    var seen = std.StringHashMap(void).init(a);
    while (references.next()) |reference| {
        if (!std.mem.startsWith(u8, reference, "$(LIB_") or !std.mem.endsWith(u8, reference, "CFILES)"))
            fail("unexpected CSOURCES syntax: {s}", .{reference});
        const name = reference[2 .. reference.len - 1];
        const list = assignments.get(name) orelse fail("missing CSOURCES list: {s}", .{name});
        var names = std.mem.tokenizeAny(u8, list, " \t\r");
        while (names.next()) |filename| {
            if (!std.mem.endsWith(u8, filename, ".c") or filename.len <= 2)
                fail("unexpected C filename: {s}", .{filename});
            for (filename[0 .. filename.len - 2]) |c| {
                if (!std.ascii.isAlphanumeric(c) and c != '_' and c != '/' and c != '-')
                    fail("unexpected C filename: {s}", .{filename});
            }
            const path = try std.fs.path.join(a, &.{ "vendor/curl/lib", filename });
            const stat = std.fs.cwd().statFile(path) catch |err|
                fail("source {s}: {s}", .{ path, @errorName(err) });
            if (stat.kind != .file) fail("source is not a regular file: {s}", .{path});
            if (seen.contains(filename)) fail("duplicate curl source: {s}", .{filename});
            try seen.put(filename, {});
            try files.append(a, filename);
        }
    }
    if (files.items.len == 0) fail("empty curl source list", .{});
    var hash: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(raw, &hash, .{});
    var result: std.ArrayList(u8) = .empty;
    // Preserve the original generated file's historical attribution byte-for-byte.
    // The current regeneration command is this Zig tool (see BUILDING.md).
    try result.appendSlice(a, try std.fmt.allocPrint(
        a,
        "// Generated by native/generate-curl-sources.py; do not edit.\n" ++
            "// curl 8.22.0, vendor/curl/lib/Makefile.inc (curl license).\n" ++
            "// SHA-256: {s}\n" ++
            "pub const sources: []const []const u8 = &.{{\n",
        .{std.fmt.bytesToHex(hash, .lower)},
    ));
    for (files.items) |filename| try result.appendSlice(a, try std.fmt.allocPrint(a, "    \"{s}\",\n", .{filename}));
    try result.appendSlice(a, "};\n");
    const destination = "native/curl-sources.zig";
    if (check) {
        const existing = std.fs.cwd().readFileAlloc(a, destination, 1024 * 1024) catch |err|
            fail("read {s}: {s}; regenerate with zig run native/generate-curl-sources.zig", .{ destination, @errorName(err) });
        if (!std.mem.eql(u8, existing, result.items))
            fail("curl manifest drift; run zig run native/generate-curl-sources.zig and review the diff", .{});
    } else {
        try std.fs.cwd().writeFile(.{ .sub_path = destination, .data = result.items });
    }
    try std.fs.File.stdout().writeAll(try std.fmt.allocPrint(a, "{s} {d} curl C sources\n", .{ if (check) "checked" else "generated", files.items.len }));
}
